### ISSUE TITLE
Duplicate Autolathe entries

### ISSUE THREAD

**Issue by caballs** [ShadowStation/ShadowStation#128] opened 2019-08-22 01:52 UTC
Issue reported from  Round ID: 530 (Shadow Station)

Reporting client version: 512

[Round ID]: # 560

[Reproduction]: # Autolathe has a duplicate, misspelt version of itself within the technology listings. Both boards are identical (?)
![image](https://user-images.githubusercontent.com/31574778/63479914-fdc41700-c45d-11e9-9e58-5e1213c56779.png)

![image](https://user-images.githubusercontent.com/31574778/63479921-01579e00-c45e-11e9-9aee-1cca819585ad.png)

**Comment by ShrkByte** [comment] 2019-08-22 05:03
This is not a bug. It is in fact a feature. The Autoylathe (Au-toy-lathe) is used to print toys, figurines and other stuff like that.

Closing.

**Closed by ShrkByte** 2019-08-22 05:03 UTC
