### ISSUE TITLE
Huge Atmos bug - NO2 not venting into space

### ISSUE THREAD

**Issue by ThePeaceGiver** [ShadowStation/ShadowStation#169] opened 2019-09-07 14:50 UTC
Round ID: 644

In two shifts, the station began experiencing floodings of NO2 into the atmosphere. While this can be explained by ruptures in atmos, in this round, departures and dorms started flooding, both after getting breached by space carp. departures' NO2 levels kept climbing, despite the breach not being fixed. Attached are two screenshots of departures before and during emergency shuttle docking.
![image](https://user-images.githubusercontent.com/54846998/64476484-85fd2880-d18f-11e9-8c5c-7bc55fa27baf.png)
![image](https://user-images.githubusercontent.com/54846998/64476495-96150800-d18f-11e9-82f2-2aad06a7a5cc.png)

**Comment by ShrkByte** [comment] 2019-09-07 14:52
Round ID?

**Comment by ThePeaceGiver** [comment] 2019-09-07 14:52
didn't post the ID for some reason

**Comment by Zaiakusin** [comment] 2019-09-07 16:05
I checked Pubby map to see if there were any pipes misconfigured.  Everything checks out.  There's no logical way that only Dorms and Departures would flood while leaving sec alone from inside the station.  Also, from what I know about atmos... Which is high pressure moves to low...  This would mean that all of the z-levels space that was open to the gas miner was compleaty filled with NO2

**Comment by ThePeaceGiver** [comment] 2019-09-07 16:54
That's the thing, the flooding began ONLY after a breach occured, and nowhere else.

**Comment by Zaiakusin** [comment] 2019-09-07 17:18
Which leads me to think that all of space...or atleast the space around the breaches, was at a really high pressure for NO2

**Comment by ShrkByte** [comment] 2019-09-07 17:22
Further testing required. I'm unable to run tests right now, could someone with an intricate knowledge of atmos please run some tests?

**Comment by Zaiakusin** [comment] 2019-09-07 19:08
Im recreating it with a gasminer in NO2, tank breach and a breach in both departures and dorms....
Goina let it run a while.  But from initial scanning and checking, the gasminer is able to stablize the tank pressure as its vented but as soon as the gas hits space, it is just gone...no pressure readings...

And im only partially sure im testing this right....

**Comment by ShrkByte** [comment] 2019-09-07 21:15
when gasses hit a space turf they're deleted. Space isn't a volume that can be filled by a gas.

**Comment by Zaiakusin** [comment] 2019-09-07 22:34
Ok, after 3 hours of testing with nothing but the breaches, nothing happened.
I decided to see what would happen if I put the NO2 straight into the breathing air loop and that's when it happened.  The low pressure areas where the breaches were drew the NO2 straight to those areas and flooded them rapidly.  It replaced the O2 and N2 which was being vented to space and being replaced by NO2 which is why the concentration was continuously going up.  The Gas Miner, while not directly responsible for this, played its part by giving an unlimited supply of NO2 at a stable pressure, despite the tank being breached.
So, it looks like someone in this round attempted to gas the station(Accidentally or purposefully) but the carps saved everyone from it.  Go figure.
Even with this happening, once the breached areas got to a stupid high concentration of NO2, the rest of the station started to flood with it as well.  But that was close to 90% NO2 and took almost a hour to get to that point.

**Comment by ShrkByte** [comment] 2019-09-07 22:50
Testing leads us to believe that this is in fact not a bug, but is actually the system working as intended. Closing.

**Closed by ShrkByte** 2019-09-07 22:50 UTC
Labels: Not A Bug
